title: 
description: Yulian's Blog
url: xiayulian.com
permalink: /:title.html

author: 夏雨莲
author-img: 
about-author: 天淡云闲，列长空数行新雁
facebook: 
github: Yulianxia
email: ylxia.de@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

