title: 春风风人
description: > # this means to ignore newlines until "baseurl:"
  test
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: 夏 # add your name
author-img:  # add your photo
about-author: 总算博客设置有点眉目了. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
