title: TEST
description: test
url: xiayulian.com


author: 狂躁的电脑白痴
author-img: 
about-author: 一切困难解决后才是纸老虎
facebook: 
github: 
email: ylxia.de@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

theme: jekyll-theme-cayman
